// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "auth/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRegistrationServiceMock is an autogenerated mock type for the IUserRegistrationService type
type UserRegistrationServiceMock struct {
	mock.Mock
}

type UserRegistrationServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRegistrationServiceMock) EXPECT() *UserRegistrationServiceMock_Expecter {
	return &UserRegistrationServiceMock_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function with given fields: email, password
func (_m *UserRegistrationServiceMock) AuthenticateUser(email string, password string) (*entity.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entity.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entity.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRegistrationServiceMock_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type UserRegistrationServiceMock_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *UserRegistrationServiceMock_Expecter) AuthenticateUser(email interface{}, password interface{}) *UserRegistrationServiceMock_AuthenticateUser_Call {
	return &UserRegistrationServiceMock_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", email, password)}
}

func (_c *UserRegistrationServiceMock_AuthenticateUser_Call) Run(run func(email string, password string)) *UserRegistrationServiceMock_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *UserRegistrationServiceMock_AuthenticateUser_Call) Return(_a0 *entity.User, _a1 error) *UserRegistrationServiceMock_AuthenticateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRegistrationServiceMock_AuthenticateUser_Call) RunAndReturn(run func(string, string) (*entity.User, error)) *UserRegistrationServiceMock_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: email, password, fullName
func (_m *UserRegistrationServiceMock) RegisterUser(email string, password string, fullName string) (*entity.User, error) {
	ret := _m.Called(email, password, fullName)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*entity.User, error)); ok {
		return rf(email, password, fullName)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *entity.User); ok {
		r0 = rf(email, password, fullName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(email, password, fullName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRegistrationServiceMock_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type UserRegistrationServiceMock_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - email string
//   - password string
//   - fullName string
func (_e *UserRegistrationServiceMock_Expecter) RegisterUser(email interface{}, password interface{}, fullName interface{}) *UserRegistrationServiceMock_RegisterUser_Call {
	return &UserRegistrationServiceMock_RegisterUser_Call{Call: _e.mock.On("RegisterUser", email, password, fullName)}
}

func (_c *UserRegistrationServiceMock_RegisterUser_Call) Run(run func(email string, password string, fullName string)) *UserRegistrationServiceMock_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRegistrationServiceMock_RegisterUser_Call) Return(_a0 *entity.User, _a1 error) *UserRegistrationServiceMock_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRegistrationServiceMock_RegisterUser_Call) RunAndReturn(run func(string, string, string) (*entity.User, error)) *UserRegistrationServiceMock_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRegistrationServiceMock creates a new instance of UserRegistrationServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegistrationServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegistrationServiceMock {
	mock := &UserRegistrationServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
