// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	service "auth/domain/service"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TokenServiceMock is an autogenerated mock type for the ITokenService type
type TokenServiceMock struct {
	mock.Mock
}

type TokenServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceMock) EXPECT() *TokenServiceMock_Expecter {
	return &TokenServiceMock_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function with given fields: userID, email
func (_m *TokenServiceMock) GenerateAccessToken(userID uuid.UUID, email string) (string, error) {
	ret := _m.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (string, error)); ok {
		return rf(userID, email)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) string); ok {
		r0 = rf(userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type TokenServiceMock_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - email string
func (_e *TokenServiceMock_Expecter) GenerateAccessToken(userID interface{}, email interface{}) *TokenServiceMock_GenerateAccessToken_Call {
	return &TokenServiceMock_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, email)}
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) Run(run func(userID uuid.UUID, email string)) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) Return(_a0 string, _a1 error) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_GenerateAccessToken_Call) RunAndReturn(run func(uuid.UUID, string) (string, error)) *TokenServiceMock_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function with given fields: userID, email
func (_m *TokenServiceMock) GenerateRefreshToken(userID uuid.UUID, email string) (string, error) {
	ret := _m.Called(userID, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (string, error)); ok {
		return rf(userID, email)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) string); ok {
		r0 = rf(userID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type TokenServiceMock_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - email string
func (_e *TokenServiceMock_Expecter) GenerateRefreshToken(userID interface{}, email interface{}) *TokenServiceMock_GenerateRefreshToken_Call {
	return &TokenServiceMock_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", userID, email)}
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) Run(run func(userID uuid.UUID, email string)) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) Return(_a0 string, _a1 error) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_GenerateRefreshToken_Call) RunAndReturn(run func(uuid.UUID, string) (string, error)) *TokenServiceMock_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessTokenExpiry provides a mock function with no fields
func (_m *TokenServiceMock) GetAccessTokenExpiry() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccessTokenExpiry")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// TokenServiceMock_GetAccessTokenExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessTokenExpiry'
type TokenServiceMock_GetAccessTokenExpiry_Call struct {
	*mock.Call
}

// GetAccessTokenExpiry is a helper method to define mock.On call
func (_e *TokenServiceMock_Expecter) GetAccessTokenExpiry() *TokenServiceMock_GetAccessTokenExpiry_Call {
	return &TokenServiceMock_GetAccessTokenExpiry_Call{Call: _e.mock.On("GetAccessTokenExpiry")}
}

func (_c *TokenServiceMock_GetAccessTokenExpiry_Call) Run(run func()) *TokenServiceMock_GetAccessTokenExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenServiceMock_GetAccessTokenExpiry_Call) Return(_a0 time.Duration) *TokenServiceMock_GetAccessTokenExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenServiceMock_GetAccessTokenExpiry_Call) RunAndReturn(run func() time.Duration) *TokenServiceMock_GetAccessTokenExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenExpiry provides a mock function with no fields
func (_m *TokenServiceMock) GetRefreshTokenExpiry() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenExpiry")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// TokenServiceMock_GetRefreshTokenExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenExpiry'
type TokenServiceMock_GetRefreshTokenExpiry_Call struct {
	*mock.Call
}

// GetRefreshTokenExpiry is a helper method to define mock.On call
func (_e *TokenServiceMock_Expecter) GetRefreshTokenExpiry() *TokenServiceMock_GetRefreshTokenExpiry_Call {
	return &TokenServiceMock_GetRefreshTokenExpiry_Call{Call: _e.mock.On("GetRefreshTokenExpiry")}
}

func (_c *TokenServiceMock_GetRefreshTokenExpiry_Call) Run(run func()) *TokenServiceMock_GetRefreshTokenExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenServiceMock_GetRefreshTokenExpiry_Call) Return(_a0 time.Duration) *TokenServiceMock_GetRefreshTokenExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenServiceMock_GetRefreshTokenExpiry_Call) RunAndReturn(run func() time.Duration) *TokenServiceMock_GetRefreshTokenExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *TokenServiceMock) ValidateToken(tokenString string) (*service.TokenClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *service.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.TokenClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *service.TokenClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type TokenServiceMock_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *TokenServiceMock_Expecter) ValidateToken(tokenString interface{}) *TokenServiceMock_ValidateToken_Call {
	return &TokenServiceMock_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *TokenServiceMock_ValidateToken_Call) Run(run func(tokenString string)) *TokenServiceMock_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenServiceMock_ValidateToken_Call) Return(_a0 *service.TokenClaims, _a1 error) *TokenServiceMock_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_ValidateToken_Call) RunAndReturn(run func(string) (*service.TokenClaims, error)) *TokenServiceMock_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenServiceMock creates a new instance of TokenServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceMock {
	mock := &TokenServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
