// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	repository "auth/domain/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RefreshTokenRepositoryMock is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepositoryMock struct {
	mock.Mock
}

type RefreshTokenRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepositoryMock) EXPECT() *RefreshTokenRepositoryMock_Expecter {
	return &RefreshTokenRepositoryMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: token
func (_m *RefreshTokenRepositoryMock) Delete(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RefreshTokenRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *RefreshTokenRepositoryMock_Expecter) Delete(token interface{}) *RefreshTokenRepositoryMock_Delete_Call {
	return &RefreshTokenRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *RefreshTokenRepositoryMock_Delete_Call) Run(run func(token string)) *RefreshTokenRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RefreshTokenRepositoryMock_Delete_Call) Return(_a0 error) *RefreshTokenRepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepositoryMock_Delete_Call) RunAndReturn(run func(string) error) *RefreshTokenRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: userID
func (_m *RefreshTokenRepositoryMock) DeleteByUserID(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepositoryMock_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type RefreshTokenRepositoryMock_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *RefreshTokenRepositoryMock_Expecter) DeleteByUserID(userID interface{}) *RefreshTokenRepositoryMock_DeleteByUserID_Call {
	return &RefreshTokenRepositoryMock_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", userID)}
}

func (_c *RefreshTokenRepositoryMock_DeleteByUserID_Call) Run(run func(userID uuid.UUID)) *RefreshTokenRepositoryMock_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *RefreshTokenRepositoryMock_DeleteByUserID_Call) Return(_a0 error) *RefreshTokenRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepositoryMock_DeleteByUserID_Call) RunAndReturn(run func(uuid.UUID) error) *RefreshTokenRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with no fields
func (_m *RefreshTokenRepositoryMock) DeleteExpired() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepositoryMock_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type RefreshTokenRepositoryMock_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
func (_e *RefreshTokenRepositoryMock_Expecter) DeleteExpired() *RefreshTokenRepositoryMock_DeleteExpired_Call {
	return &RefreshTokenRepositoryMock_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired")}
}

func (_c *RefreshTokenRepositoryMock_DeleteExpired_Call) Run(run func()) *RefreshTokenRepositoryMock_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RefreshTokenRepositoryMock_DeleteExpired_Call) Return(_a0 error) *RefreshTokenRepositoryMock_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepositoryMock_DeleteExpired_Call) RunAndReturn(run func() error) *RefreshTokenRepositoryMock_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: token
func (_m *RefreshTokenRepositoryMock) Find(token string) (*repository.RefreshToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *repository.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.RefreshToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.RefreshToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepositoryMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type RefreshTokenRepositoryMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - token string
func (_e *RefreshTokenRepositoryMock_Expecter) Find(token interface{}) *RefreshTokenRepositoryMock_Find_Call {
	return &RefreshTokenRepositoryMock_Find_Call{Call: _e.mock.On("Find", token)}
}

func (_c *RefreshTokenRepositoryMock_Find_Call) Run(run func(token string)) *RefreshTokenRepositoryMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RefreshTokenRepositoryMock_Find_Call) Return(_a0 *repository.RefreshToken, _a1 error) *RefreshTokenRepositoryMock_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepositoryMock_Find_Call) RunAndReturn(run func(string) (*repository.RefreshToken, error)) *RefreshTokenRepositoryMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: userID, token, expiresAt
func (_m *RefreshTokenRepositoryMock) Save(userID uuid.UUID, token string, expiresAt int64) error {
	ret := _m.Called(userID, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int64) error); ok {
		r0 = rf(userID, token, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepositoryMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RefreshTokenRepositoryMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - userID uuid.UUID
//   - token string
//   - expiresAt int64
func (_e *RefreshTokenRepositoryMock_Expecter) Save(userID interface{}, token interface{}, expiresAt interface{}) *RefreshTokenRepositoryMock_Save_Call {
	return &RefreshTokenRepositoryMock_Save_Call{Call: _e.mock.On("Save", userID, token, expiresAt)}
}

func (_c *RefreshTokenRepositoryMock_Save_Call) Run(run func(userID uuid.UUID, token string, expiresAt int64)) *RefreshTokenRepositoryMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *RefreshTokenRepositoryMock_Save_Call) Return(_a0 error) *RefreshTokenRepositoryMock_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepositoryMock_Save_Call) RunAndReturn(run func(uuid.UUID, string, int64) error) *RefreshTokenRepositoryMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenRepositoryMock creates a new instance of RefreshTokenRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepositoryMock {
	mock := &RefreshTokenRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
