// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "auth/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	valueobject "auth/domain/valueobject"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: user
func (_m *UserRepositoryMock) Create(user *entity.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *entity.User
func (_e *UserRepositoryMock_Expecter) Create(user interface{}) *UserRepositoryMock_Create_Call {
	return &UserRepositoryMock_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *UserRepositoryMock_Create_Call) Run(run func(user *entity.User)) *UserRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *UserRepositoryMock_Create_Call) Return(_a0 error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_Create_Call) RunAndReturn(run func(*entity.User) error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *UserRepositoryMock) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *UserRepositoryMock_Expecter) Delete(id interface{}) *UserRepositoryMock_Delete_Call {
	return &UserRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *UserRepositoryMock_Delete_Call) Run(run func(id uuid.UUID)) *UserRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepositoryMock_Delete_Call) Return(_a0 error) *UserRepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_Delete_Call) RunAndReturn(run func(uuid.UUID) error) *UserRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function with given fields: email
func (_m *UserRepositoryMock) ExistsByEmail(email *valueobject.Email) (bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*valueobject.Email) (bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(*valueobject.Email) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*valueobject.Email) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type UserRepositoryMock_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - email *valueobject.Email
func (_e *UserRepositoryMock_Expecter) ExistsByEmail(email interface{}) *UserRepositoryMock_ExistsByEmail_Call {
	return &UserRepositoryMock_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", email)}
}

func (_c *UserRepositoryMock_ExistsByEmail_Call) Run(run func(email *valueobject.Email)) *UserRepositoryMock_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*valueobject.Email))
	})
	return _c
}

func (_c *UserRepositoryMock_ExistsByEmail_Call) Return(_a0 bool, _a1 error) *UserRepositoryMock_ExistsByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_ExistsByEmail_Call) RunAndReturn(run func(*valueobject.Email) (bool, error)) *UserRepositoryMock_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: email
func (_m *UserRepositoryMock) FindByEmail(email *valueobject.Email) (*entity.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*valueobject.Email) (*entity.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(*valueobject.Email) *entity.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*valueobject.Email) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepositoryMock_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email *valueobject.Email
func (_e *UserRepositoryMock_Expecter) FindByEmail(email interface{}) *UserRepositoryMock_FindByEmail_Call {
	return &UserRepositoryMock_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *UserRepositoryMock_FindByEmail_Call) Run(run func(email *valueobject.Email)) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*valueobject.Email))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByEmail_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindByEmail_Call) RunAndReturn(run func(*valueobject.Email) (*entity.User, error)) *UserRepositoryMock_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *UserRepositoryMock) FindByID(id uuid.UUID) (*entity.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entity.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *UserRepositoryMock_Expecter) FindByID(id interface{}) *UserRepositoryMock_FindByID_Call {
	return &UserRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *UserRepositoryMock_FindByID_Call) Run(run func(id uuid.UUID)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) RunAndReturn(run func(uuid.UUID) (*entity.User, error)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: user
func (_m *UserRepositoryMock) Update(user *entity.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *entity.User
func (_e *UserRepositoryMock_Expecter) Update(user interface{}) *UserRepositoryMock_Update_Call {
	return &UserRepositoryMock_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *UserRepositoryMock_Update_Call) Run(run func(user *entity.User)) *UserRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *UserRepositoryMock_Update_Call) Return(_a0 error) *UserRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_Update_Call) RunAndReturn(run func(*entity.User) error) *UserRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
