name: Docker - Auth Service

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  security-events: write
  packages: read

jobs:
  call-docker-workflow:
    uses: ./.github/workflows/docker-template.yml
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      service_name: auth
      service_path: auth
      docker_image: hanapi23/auth-service
      docker_platforms: linux/amd64,linux/arm64
