name: CI - Auth Service

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'auth/**'
      - '.github/workflows/auth-ci.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'auth/**'
      - '.github/workflows/auth-ci.yml'
      - '.github/workflows/ci-template.yml'

permissions:
  contents: read
  security-events: write

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: auth
      service_path: auth
      go_version: '1.23'
